// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bad-any.proto

package io.confluent.examples.clients.proto;

/**
 * Protobuf type {@code io.confluent.examples.clients.proto.BadAny}
 */
public  final class BadAny extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.confluent.examples.clients.proto.BadAny)
    BadAnyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BadAny.newBuilder() to construct.
  private BadAny(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BadAny() {
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BadAny();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BadAny(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (eventData_ != null) {
              subBuilder = eventData_.toBuilder();
            }
            eventData_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eventData_);
              eventData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.confluent.examples.clients.proto.BadAnyOuterClass.internal_static_io_confluent_examples_clients_proto_BadAny_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.confluent.examples.clients.proto.BadAnyOuterClass.internal_static_io_confluent_examples_clients_proto_BadAny_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.confluent.examples.clients.proto.BadAny.class, io.confluent.examples.clients.proto.BadAny.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.Any eventData_;
  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   * @return Whether the eventData field is set.
   */
  public boolean hasEventData() {
    return eventData_ != null;
  }
  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   * @return The eventData.
   */
  public com.google.protobuf.Any getEventData() {
    return eventData_ == null ? com.google.protobuf.Any.getDefaultInstance() : eventData_;
  }
  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   */
  public com.google.protobuf.AnyOrBuilder getEventDataOrBuilder() {
    return getEventData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (eventData_ != null) {
      output.writeMessage(2, getEventData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (eventData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEventData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.confluent.examples.clients.proto.BadAny)) {
      return super.equals(obj);
    }
    io.confluent.examples.clients.proto.BadAny other = (io.confluent.examples.clients.proto.BadAny) obj;

    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasEventData() != other.hasEventData()) return false;
    if (hasEventData()) {
      if (!getEventData()
          .equals(other.getEventData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasEventData()) {
      hash = (37 * hash) + EVENT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getEventData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.confluent.examples.clients.proto.BadAny parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.confluent.examples.clients.proto.BadAny parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.confluent.examples.clients.proto.BadAny parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.confluent.examples.clients.proto.BadAny prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.confluent.examples.clients.proto.BadAny}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.confluent.examples.clients.proto.BadAny)
      io.confluent.examples.clients.proto.BadAnyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.examples.clients.proto.BadAnyOuterClass.internal_static_io_confluent_examples_clients_proto_BadAny_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.examples.clients.proto.BadAnyOuterClass.internal_static_io_confluent_examples_clients_proto_BadAny_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.examples.clients.proto.BadAny.class, io.confluent.examples.clients.proto.BadAny.Builder.class);
    }

    // Construct using io.confluent.examples.clients.proto.BadAny.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      message_ = "";

      if (eventDataBuilder_ == null) {
        eventData_ = null;
      } else {
        eventData_ = null;
        eventDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.confluent.examples.clients.proto.BadAnyOuterClass.internal_static_io_confluent_examples_clients_proto_BadAny_descriptor;
    }

    @java.lang.Override
    public io.confluent.examples.clients.proto.BadAny getDefaultInstanceForType() {
      return io.confluent.examples.clients.proto.BadAny.getDefaultInstance();
    }

    @java.lang.Override
    public io.confluent.examples.clients.proto.BadAny build() {
      io.confluent.examples.clients.proto.BadAny result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.confluent.examples.clients.proto.BadAny buildPartial() {
      io.confluent.examples.clients.proto.BadAny result = new io.confluent.examples.clients.proto.BadAny(this);
      result.message_ = message_;
      if (eventDataBuilder_ == null) {
        result.eventData_ = eventData_;
      } else {
        result.eventData_ = eventDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.confluent.examples.clients.proto.BadAny) {
        return mergeFrom((io.confluent.examples.clients.proto.BadAny)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.confluent.examples.clients.proto.BadAny other) {
      if (other == io.confluent.examples.clients.proto.BadAny.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasEventData()) {
        mergeEventData(other.getEventData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.confluent.examples.clients.proto.BadAny parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.confluent.examples.clients.proto.BadAny) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any eventData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> eventDataBuilder_;
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     * @return Whether the eventData field is set.
     */
    public boolean hasEventData() {
      return eventDataBuilder_ != null || eventData_ != null;
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     * @return The eventData.
     */
    public com.google.protobuf.Any getEventData() {
      if (eventDataBuilder_ == null) {
        return eventData_ == null ? com.google.protobuf.Any.getDefaultInstance() : eventData_;
      } else {
        return eventDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public Builder setEventData(com.google.protobuf.Any value) {
      if (eventDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        eventDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public Builder setEventData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (eventDataBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        eventDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public Builder mergeEventData(com.google.protobuf.Any value) {
      if (eventDataBuilder_ == null) {
        if (eventData_ != null) {
          eventData_ =
            com.google.protobuf.Any.newBuilder(eventData_).mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        eventDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public Builder clearEventData() {
      if (eventDataBuilder_ == null) {
        eventData_ = null;
        onChanged();
      } else {
        eventData_ = null;
        eventDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public com.google.protobuf.Any.Builder getEventDataBuilder() {
      
      onChanged();
      return getEventDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getEventDataOrBuilder() {
      if (eventDataBuilder_ != null) {
        return eventDataBuilder_.getMessageOrBuilder();
      } else {
        return eventData_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : eventData_;
      }
    }
    /**
     * <code>.google.protobuf.Any event_data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getEventDataFieldBuilder() {
      if (eventDataBuilder_ == null) {
        eventDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getEventData(),
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      return eventDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.confluent.examples.clients.proto.BadAny)
  }

  // @@protoc_insertion_point(class_scope:io.confluent.examples.clients.proto.BadAny)
  private static final io.confluent.examples.clients.proto.BadAny DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.confluent.examples.clients.proto.BadAny();
  }

  public static io.confluent.examples.clients.proto.BadAny getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BadAny>
      PARSER = new com.google.protobuf.AbstractParser<BadAny>() {
    @java.lang.Override
    public BadAny parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BadAny(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BadAny> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BadAny> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.confluent.examples.clients.proto.BadAny getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

