// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bad-any.proto

package io.confluent.examples.clients.proto;

public final class BadAnyOuterClass {
  private BadAnyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_examples_clients_proto_BadAny_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_examples_clients_proto_BadAny_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbad-any.proto\022#io.confluent.examples.c" +
      "lients.proto\032\031google/protobuf/any.proto\"" +
      "C\n\006BadAny\022\017\n\007message\030\001 \001(\t\022(\n\nevent_data" +
      "\030\002 \001(\0132\024.google.protobuf.AnyB\'\n#io.confl" +
      "uent.examples.clients.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_io_confluent_examples_clients_proto_BadAny_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_examples_clients_proto_BadAny_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_examples_clients_proto_BadAny_descriptor,
        new java.lang.String[] { "Message", "EventData", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
