// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bad-any.proto

package io.confluent.examples.clients.proto;

public interface BadAnyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.confluent.examples.clients.proto.BadAny)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   * @return Whether the eventData field is set.
   */
  boolean hasEventData();
  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   * @return The eventData.
   */
  com.google.protobuf.Any getEventData();
  /**
   * <code>.google.protobuf.Any event_data = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getEventDataOrBuilder();
}
