// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: good.proto

package io.confluent.examples.clients.proto;

public final class Good {
  private Good() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_examples_clients_proto_GoodStringMulti_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_examples_clients_proto_GoodStringMulti_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_examples_clients_proto_GoodString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_examples_clients_proto_GoodString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngood.proto\022#io.confluent.examples.clie" +
      "nts.proto\"\"\n\017GoodStringMulti\022\017\n\007message\030" +
      "\001 \003(\t\"\035\n\nGoodString\022\017\n\007message\030\001 \001(\tB\'\n#" +
      "io.confluent.examples.clients.protoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_confluent_examples_clients_proto_GoodStringMulti_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_examples_clients_proto_GoodStringMulti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_examples_clients_proto_GoodStringMulti_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_io_confluent_examples_clients_proto_GoodString_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_confluent_examples_clients_proto_GoodString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_examples_clients_proto_GoodString_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
