// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: good.proto

package io.confluent.examples.clients.proto;

public interface GoodStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.confluent.examples.clients.proto.GoodString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
