// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: good.proto

package io.confluent.examples.clients.proto;

public interface GoodStringMultiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.confluent.examples.clients.proto.GoodStringMulti)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string message = 1;</code>
   * @return A list containing the message.
   */
  java.util.List<java.lang.String>
      getMessageList();
  /**
   * <code>repeated string message = 1;</code>
   * @return The count of message.
   */
  int getMessageCount();
  /**
   * <code>repeated string message = 1;</code>
   * @param index The index of the element to return.
   * @return The message at the given index.
   */
  java.lang.String getMessage(int index);
  /**
   * <code>repeated string message = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the message at the given index.
   */
  com.google.protobuf.ByteString
      getMessageBytes(int index);
}
